Dev
DonnyTheTalker/Groebner-Basis-Cpp pull request #1
Opened 2024-01-14 17:47 UTC by DonnyTheTalker

2024-03-08 09:07 UTC, DimaTrushin requested changes
У тебя неверно залились google tests. Они добавились не в виде подмодуля. В итоге у меня 100'000 строчек кода на ревью. И все притормаживает знатно. Поправь, убери лишнее. Такая же проблема была у CuteHater она справилась с этой бедой.

Все таки из-за слайд-шоу буду ждать выпиливания gtest-ов из репозитория.

2024-03-08 09:07 UTC, DimaTrushin commented on .gitmodules
У тебя неверно залились google tests. Они добавились не в виде подмодуля. В итоге у меня 100'000 строчек кода на ревью. И все притормаживает знатно. Поправь, убери лишнее. Такая же проблема была у CuteHater она справилась с этой бедой.

2024-03-09 08:02 UTC, DonnyTheTalker commented on .gitmodules
Поправил

2024-03-09 13:07 UTC, DimaTrushin commented on .clang-tidy
> +readability-use-anyofallof'
LOL clang-tidy есть, а clang-format нет =)

Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-03-09 13:07 UTC, DimaTrushin commented on .gitignore
> +cmake-build-debug/
Ты только в дебаге собираешь? Почему только такой игнор?

2024-03-09 13:07 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Добавь строчку
```cpp
set(CMAKE_CXX_STANDARD_REQUIRED True)
```
А то cmake разрешено откатиться на более низкий стандарт.

2024-03-09 13:07 UTC, DimaTrushin commented on src/CMakeLists.txt
> +add_library(src STATIC ${SOURCE_FILES} ${HEADER_FILES})
Не надо добавлять h файлы в add_executable или add_library

2024-03-09 13:07 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +class GroebnerBuilder {
Плохое название класса, это не Builder, а скорее Algorithm или что-то в этом духе. Потому что ты не только для построения используешь этот класс, а вообще хранишь все возможные алгоритмы релевантные для гребнера.

2024-03-09 13:07 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +class GroebnerBuilder {
Плохое название класса, это не Builder, а скорее Algorithm или что-то в этом духе. Потому что ты не только для построения используешь этот класс, а вообще хранишь все возможные алгоритмы релевантные для гребнера.

2024-03-09 16:36 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Из самого главного мне не нравятся несколько важных вещей.
1) У тебя некорретная семантика у MonomialDegree, Modular из-за хранения константного данного в виде поля. В случае Modular надо перенести это в шаблонный параметр и пусть компилятор разбирается. А в случае MonomialDegree там есть два подхода, либо убрать ограничение совсем. Либо все перенести в compile-time.
2) У тебя какая-то дичь в операторах сравнения.
3) Мономы с коэффициентами сравнивать НЕ корректно. Все порядки по сути для MonomialDegree. Просто я мономами называют то, что ты называешь MonomialDegree, а твои Monomial я называю Terrms. Потому мономиальный порядок у тебя превратился не в то, что надо. Кроме того у тебя какой-то странный straight order, в котором isEqual не эквивалентно !isLess(lhs, rhs) && !isLess(rhs, lhs).

Из важного, проследи за всеми инвариантами для всех классов. У тебя порой такие дыры висят в поддержке инвариантов, что часть операций просто не верно работает. Как например сравнение многочленов на равенство. И еще я более чем уверен, что сложение у тебя тоже работает только для отсортированных многочленов, что плохо.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    static PolySystem<Field, Comparator> Build(const PolySystem<Field, Comparator> &system, bool reduce = false);
1) Плохое название алгоритма. Что ты тут строишь? Сделай хотя бы BuildGB.
2) Плохой интерфейс, никогда не делай булев флаг. Вот смотри как будет выглядеть код клиента
```cpp
auto g = GroebnerBuilder::Build(f, true);
```
Что значит это true? А что значит false? А еще никто не мешает написать Build(f, 20) И это тоже скомпилится без единого зазрения совести. Если тебе нужен статус или параметр с определенным значением для набора случаев, то заводи enum class
```cpp
enum class AutoReduction {Enabled, Disabled};
// Тогда зовущий будет писать
auto g = GroebnerBuilder::Build(f, AutoReduction::Enabled);
```
И это будет говорить о многом сразу же. Но я угадываю сейчас для чего нужен этот флаг, потому надо названия и опции подобрать соответствующим образом.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    static Monomial<Field> FindLcm(const Monomial<Field> &lhs, const Monomial<Field> &rhs);
Уже вижу проблемы. Lcm с коэффициентом -- плохая вещь. Ты вряд ли сможешь соблюсти инвариант Lcm * Gcd = m1 * m2. И еще коэффициент может быть нулевым и тогда вообще все поедет.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +
Глобально не хватает inplace операций, когда ты меняешь то самое множество или многочлен, который тебе дали в виде аргумента.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    static Polynomial<Field, Comparator> ReducePolynomial(Polynomial<Field, Comparator> poly,
Почему вдруг ты тут принимаешь многочлен by value? Если что из аргумента функции не работает nrvo.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +template<IsField Field, IsComparator Comparator>
Нет смысла определять шаблоны снаружи. Определяй все шаблоны при объявлении. Так у тебя меньше будет мусорного кода.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    // TODO log this and return 0 as polynomial
Плохая идея, лучше верни пустое множество.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    assert(!system.IsEmpty() && "Can't find basis in empty system");
Плохая идея падать на пустом множестве, все функции из этого класса должны быть безопасными, в том смысле, что они должна отрабатывать на любом входе. Внутри они могут использовать приватные не безопасные методы, если это позволит избавиться от проверок и что-то ускорить. Но тогда перед их вызовом ты должен гарантировать все precondition и в этом будет задача публичных методов.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    PolySystem<Field, Comparator> result(system);
Не используй сырые имена шаблонов. Заведи в начале функции using например
```cpp
using PolySystem = PolySystem<Field, Comparator>;
```
и потом тебе не надо будет таскать миллиард параметров шаблонов друг за другом. Код будет более кратким и читаемым.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    return reduce ? ReduceBasis(result) : result;
Вот тут хорошо видно, что тебе бы нужно ReduceBasis сделать с возможностью in place иначе в случае reduce == true у тебя создается еще один новый базис. НО тут есть проблема хуже. Из-за этого у тебя компилятор не может сделать nrvo, потому что ты возвращаешь разные объекты, потому тут произойдет лишнее копирование временных объектов (ну или если повезет, то move). Никтогда не возвращай выражение, это мешает сделать nrvo. Всегда делай все манипуляции до return и потом делай return local_variable; И убедись, что тип local_variable вточности совпадает с типом возвращаемым функцией, чтобы избежать лишних операторов копирования или перемещения.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +                // TODO maybe reduce coefficient ?
Вообще очень хорошая идея всегда все старшие коэффициенты делать 1.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    assert(lhs.GetSize() == rhs.GetSize() && "Number of variables must be same");
Почему это проблема? Почему пользователь не может задать тебе моном x^2 и xy? Это плохой дизайн. Пользователь не ждет, что могомы от x и от x и y внезапно не смогут использоваться для поиска lcm.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    Field coef = lhs.GetCoef() * rhs.GetCoef();
Что если хотя бы один из коэффициентов 0? Ты обрабатываешь этот случай?

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    degree.SetSumDegree(sum_degree);
Ну это пиздец. Тут я могу установить любое значение суммы степеней и у тебя моном будет в некорректном состоянии. Никогда так не делай. Эта характеристика должна считаться конструктором и каждой мутирующей операцией.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +    return Monomial<Field>(coef, degree);
Как же меня смущает, что тут не написано
```cpp
 return Monomial<Field>(std::move(coef), std::move(degree));
```
Как минимум это значит, что у тебя все данные из degree и coef (что может быть не так фатально), лишний раз копируются в моном, а не воруются их внутренности.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +//    Monomial<Field> left_mod = lcm / lhs.GetLeader();
Зачем тебе git с его поддержкой версий, если ты оставляешь закомментированный код? Убрать. Гит помнит всю историю и хранит весь код. Если нужно поиграться, то создаешь локально тестовую ветку, там играешь, а потом через checkout пикаешь нужные файлы.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +                                                     const Monomial<Field> &lcm);
Плохой интерфейс. S-полином не должен принимать три параметра, он зависит полностью от двух многочленов. Их lcm старших мономов однозначно определен. Я могу без проблем сюда поставить некорректный моном и твой алгоритм к хуям упадет.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +                continue;
У тебя тут 4 вложенных scope. Даже в ядре Linux запрещено иметь более 3. Это требует рефакторинга.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +            const Polynomial<Field, Comparator> rem = ReducePolynomial(SPolynomial(result[i], result[j], lcm), result);
Если это оптимизация, то тогда этот метод построения S-полинома должен быть приватным.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +           (rhs * Polynomial<Field, Comparator>({lcm / rhs.GetLeader()}));
Судя по всему тебе нужен не только lcm, но и оба множителя. Тогда у тебя должен быть приватный алгоритм который считает их все в один проход и возвращает в структуре с тремя полями.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +        bool divisible = false;
Булев флаг -- частый показатель ошибки дизайна. Обычно если ты пользуешь флагом, это означает, что в этом месте должна была вызываться вспомогательная функция, которую ты не написал. А вместо флага условия остановки контролируются через return.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +            // TODO add IsDivisible method somewhere
Очень правильная мысль. Можно добавить к моному.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.h
> +
Не пиши в global namespace, заведи пространство имен для проекта и все пиши в него.

2024-03-09 16:36 UTC, DimaTrushin commented on src/FieldFwd.h
> +concept IsField = std::is_same_v<T, Modulo> || std::is_same_v<T, Rational>;
Плохой концепт. Он нагло врет пользователю. Он не проверяет является ли класс полем, он проверяет либо остатки, либо рациональные. Это плохое название. Никогда не обманывай пользователя в названии. Можешь напиать IsSupportedField, чтобы было хотя бы понятно, что это не любое поле, а только поле из списка. Кроме того, лучше завести список поддерживаемых полей и сделать что-то в таком духе
```cpp
template<class... Ts>
struct List {};

template<class T, class TList>
struct IsInListImpl : std::false_type {};

template<class T, class... Ts>
struct IsInListImpl<T, List<Ts...>> {
  static constexpr bool value = std::disjunction_v<std::is_same<T, Ts>...>;
};

template<class T, class TList>
static constexpr bool IsInList = IsInListImpl<T, TList>::value;

using SupportedFields = List<Modulo, Rational>;

template<class T>
concept IsSupportedField = IsInList<T, SupportedFields>;
```
При этом все кроме IsSupportedField  поместить в namespace detail или какое-нибудь другое вспомогательное, чтобы они не засоряли твое пространство имен.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +    const OrderType order_;
НИКОГДА не делай константные поля в классе! И зачем я только читал курс по плюсам, где я это все рассказываю?.. Ты лишаешь свой класс возможности для мува. Автоматически ВСЕ классы его содержащие становятся not-movable, что вообще не очевидно. А это большой проеб.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +    explicit Modulo(OrderType order, ValueType value = 0);
Максимально плохой дизайн. Вот что пользователь ожидает от такого конструктора
```cpp
Modulo y = Modulo(5);
```
Я бы никогда не догадался, что у тебя y будет НУЛЕМ, блять. Более того, какого хуя вообще тут делает параметр order? Почему у тебя возникают разные порядки? И почему они не являются enum class типа? Что за хуйня? Я бы ожидал видеть в начале value и только потом дефолтный порядок. Потому что я скорее хочу указать какой у меня должен быть остаток, а не как я хочу сравнивать эти остатки.

UPD: Это пиздец. Так зафакапиться с названиями, чтобы я вообще не понял что это тут такое. Но я в любом случае думаю, что лучше иметь в начале value и лишь потом modulus. И всегда и то и другое указывать явно! Иначе будет большая проблема.

И еще, раз у тебя нет длинки и у тебя все данные входят по размеру в int64_t, почему не сделать modulus шаблонным параметром, чтобы для разных оснований у тебя классы нельзя было смешивать. Тогда бы компилятор смог тебя предупреждать о подобных ошибках во время компиляции, а не в рантайме.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +    Modulo(Modulo &&other) noexcept;
Убери константные поля и все это безобразие тебе не надо будет писать. Будут годиться дефолтные версии. А они всегда работают лучше, потому что компилятор в них уверен.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +public:
Не повторяй квалификатор доступа, если он не поменялся.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +    Modulo operator-() const;
Если у тебя есть унарный минус, то стоит добавить и унарный плюс.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +    Modulo &operator+=(const Modulo &other);
Так как у тебя класс modulo состоит из двух указателей по размеру, то может быть эффективнее передавать его by value. Это стоит потестить.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +    Modulo Inverse() const;
Почему нет inplace версии?

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +    using ValueType = int64_t;
Это бигфейл. Я даже обманулся читая этот код. Подумал, а нахуя же у тебя есть еще какой-то порядок на остатках. А оказывается, это число является основанием. Так вот, это плохая тема иметь для остатка и основания потенциально разный тип (тем более не стоит их разделять названием если они одинаковые). Потому я бы ожидал, что тип у тебя один единственный Value. НО при этом у тебя основание называется modulus_.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.cpp
> +Modulo Modulo::Inverse() const {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.cpp
> +    Modulo::ValueType ExtendedFindGcd(Modulo::ValueType x, Modulo::ValueType y,
Название функции должно начинаться с глагола. То есть тут должно быть FindGcdExtended

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.cpp
> +        if (x == 0) {
поставь assert, что адресса не нулевые.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.cpp
> +    assert(order_ == other.order_ && "Orders must be equal in '='");
Плохой дизайн. Сделай Modulus шаблонным параметром. Это избавит тебя от этих костылей.
Если что это полный класс. Это означает, что у тебя даже операторы присваивания не работают для произвольных переменных класса. Это просто пиздос.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.cpp
> +    }
Никогда не оптимизируй под редкие случаи, особенно, когда эта оптимизация лишняя. Вот такой код сработает всегда:
```cpp
value_ = std::exchange(other.value_, 0);
```

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.cpp
> +    Modulo::ValueType ExtendedFindGcd(Modulo::ValueType x, Modulo::ValueType y,
1) Раз у тебя есть расширенный gcd, то имеет смысл добавить метод divide(a, b). Потому что это гипотетически может считаться быстрее, чем делать a * inverse(b). Как минимум стоит сравнить в тестах производительность.
2) А что с нерекурсивным решением?

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.cpp
> +    return temp += other;
Не делай так. Ты только что помешал nrvo. Дело в том, что оператор += возвращает Modulo&, а у тебя оператор должен вернуть Modulo (без амперсанда). Компилятор видит, что тип возвращаемого выражения отличается от типа выражения в return и НЕ делает nrvo. Потому писать надо так
```cpp
temp += other;
return temp;
```

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.h
> +    bool operator==(const Modulo &other) const;
Если есть оператор ==, то надо обязательно добавить оператор !=, но только имплементировать его надо так
```cpp
return !(*this == other);
```

2024-03-09 16:36 UTC, DimaTrushin commented on src/Modulo.cpp
> +    return order_ == other.order_ && value_ <= other.value_;
По хорошему ты должен имплементировать operator<=(a, b) через return !(b < a). НО у тебя это будет не верная имплементация. И это как раз говорит что у тебя константное данное order_ не удовлетворяет требованиям к поведению нормального value класса. Это должно быть статическое данное привязанное к классу, а не константное поле в каждой переменной.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.h
> +    using SizeType = size_t;
Ну вот тут лучше не заводить using. Просто в клиентском коде ты везде пишешь size_t явно, а не SizeType (посмотри на GroebnerBuilder класс, там ни в одном месте у тебя НЕ использован этот тип). Потому я думаю, что его лучше упразднить. Для подсчета числа штук size_t вполне подходит.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.h
> +    const SizeType n_variables_;
Что это за пиздец? Нахуя, а главное зачем тут эта константа!?
Во-первых, она дублирует данные в degrees_, потому что каждый вектор знает свой размер.
Во-вторых, это нарушает value semantics и максимально бьет тебя по жопе каждый раз, когда ты хочешь пукнуть.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.h
> +    MonomialDegree(SizeType n_variables, const std::vector<DegreeType>& degrees);
Звание на имя худшего конструктора выиграно
```cpp
MonomialDegree m(2, {1, 2, 3});
```
И привет. И как понять, что не то, иди гадай. Ну это пиздос. Но еще хуже
```cpp
MonomialDegree m(2, {1});
```
А это сработает? Если что я бы ожидал что должно, иначе я не смогу переменную сравнить с произведением двух разных переменных и вообще не смогу их вместе использовать.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.h
> +    MonomialDegree(SizeType n_variables, const std::vector<DegreeType>& degrees);
Вообще я бы посоветовал бы решить для себя, ты хочешь чтобы размер данных был известен во время компиляции или в рантайме. Если во время компиляции, то сделай этот размер шаблонным параметром. Кроме того, тогда не надо ипользовать вектор можно использовать std::array, ну или std::unique_ptr<std::array> если ты хочешь сделать легкой локальную часть и сделать дешовый мув как у вектора. Но если же этот параметр у тебя не константный, то не надо его искусственно ограничевать константным полем и везде проверять на проверочные проверки. Это просто нарушение инкапсюляции. В чем смысл был инкапсюлировать данные в класс и делать для него операции, если они не работают для произвольных членов класса?

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.h
> +    const DegreeType& operator[](size_t ind) const;
Вот уже тут ты сам не испльзуешь SizeType, это хороший показатель, что его быть не должно.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.h
> +    bool operator==(const MonomialDegree &other) const;
Отсутствие оператора != -- плохой знак. Судя по твоим выкрутасам с константными данными дефолтная имплементация может не подойти.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.cpp
> +
Больше пустых строк богу пустых строк. Блять, где clang-format?

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.cpp
> +// TODO remove this completely
Почему поддержанием этого параметра не занимаются мутирующие методы класса? Собственно для этого методы класса и нужны -- поддержка инварианта класса.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.h
> +    MonomialDegree(SizeType n_variables, const std::vector<DegreeType>& degrees);
Другая проблема этого конструктора -- принимает конкретный контейнер. А что если я сюда подставлю конвертируемый контейнер? Тогда у тебя построится временный вектор, например при написании кода
```cpp
MonomialDegree m(2, {1, 2});
```
Аргумент {1, 2} является типа std::initializer_list<int> и он не совпадает с std::vector<int64_t>, потому компилятор построит временный контейнер типа std::vector<int64_t>, и после этого ты этот временный объект передаешь по константной ссылке внутрь конструктора. И значит при присваивании этого контейнера полю данные опять оттуда копируются. То есть у тебя происходит как минимум создание одного временного объекта с аллокацией на куче и еще два копирования. Ну это привет. Либо принимай std::initializer_list<DegreeType>, либо принимай вектор по rvalue reference, чтобы можно было хотя бы украсть его внутренности.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.cpp
> +    other.degrees_.resize(n_variables_);
Вместо этого можно было бы использовать std::exchange на degrees_ и написать
```cpp
degrees_(std::exchange(other.degrees_, GetDefaultVector(n_variables_)));
// где
static std::vector<int64_t> GetDefaultVector(size_t size) {
  return std::vector<int64_t>(size, 0);
}
```
Но на мой взгляд лучше вообще убрать это говно в виде константных членов и сделать нормальное поведение этого класса.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.cpp
> +    if (this != &other) {
Убрать

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.cpp
> +    assert(ind < n_variables_ && "Out of bounds");
В целом плохая идея делать небезопасный интерфейс. Лучше  сделать метод getDegree(size_t index) и он будет возвращать хранимае значение by value если индекс в рамках массива и 0 если вне массива. Это позволит тебе безопасно пользоваться этим методом снаружи. Ну и если тебе надо добавить элемент, лучше уж сделать метод setDegree(size_t index, DegreeType degree) и этот метод будет эффективно увеличивать вектор, если надо. Ну или если ты хочешь прям использовать оператор [], то надо возвращать прокси объект, который при присваивании проверяет размер вектрра и выполняет его увеличение при необходимости.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.cpp
> +const MonomialDegree::DegreeType& MonomialDegree::operator[](size_t ind) const {
Нет смысла возвращать по константной ссылке встроенные типы. Возвращай их по значению.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialDegree.cpp
> +    return degrees_[ind];
Нужно добавить поддержку инварианта суммы степеней во все мутирующие методы.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Monomial.h
> +    Field coef_;
Плохая тема хранить коэффициент в мономе. Потому что операторы сравнения работают без коэффициента. А так тебе придется кучу костылей городить. Ну ты их и городишь.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Monomial.h
> +    Monomial<Field> &operator=(Monomial<Field> &&other) noexcept;
Какого хуя не дефолтная имплементация? У тебя же мономы обладают value semantics! Почему ты опять городишь костыли тут? Вообще когда тебе надо писать так много дефолтных конструкторов надо задуматься над смыслом своей жизни и понять, что ты все делаешь не так.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Monomial.h
> +    Monomial(Field coef, const MonomialDegree &degree);
Если MonomialDegree тяжелый тип, но легко мувается, то надо бы принимать его by rvalue reference, а не по const lvalue reference. Тогда можно будет красть его кишки. Ну или как минимум надо две версии писать. Ну либо принимать by value.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Monomial.h
> +    Field& GetCoef();
1) Плохое название для функции. Дело в том что это не функция getter, а доступ к полю класса по неконстантной ссылке, то лучше так и назвать coef() ну или если у тебя пальцы не отвалятся писать coefficient(). Тогда хотя бы название не будет врать пользователю о том, что через эту функцию можно случайно все внутри изгадить.

2) Есть куда более серьезная проблема. Если коэффициент 0, поддерживается ли какой-нибудь дополнительный инвариант (например обнуляются ли при этом степени монома?). Если есть дополнительный инвариант, то этот метод нарушает инкапсюляцию, потому что через него можно этот инвариант сломать. Это не корректный класс. Если же нет никакого дополнительного инварианта, то я бы поглядел на то, как ты будешь обрабатывать кучу левых случаев и как ты будешь боросться с разрастанием монома в памяти фиктивными переменными.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Monomial.h
> +    const MonomialDegree &GetDegree() const;
Плохое название методов. Дело в том, что ты возвращаешь не одну степень, а все степени сразу.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Monomial.h
> +    Monomial<Field> &operator-=(const Monomial<Field> &other);
Плохие операторы. Они не должны быть определены для монома с коэффициентом, потому что ты не можешь складывать любые два монома, а только мономы с согласованными переменными. Это опять говорит об ошибке дизайна, которую ты не заметил, потому что уже третий раз ее допускаешь и привык к этому говнищу. А ведь можно писать код куда проще и удобнее. Вместо этих методов должны быть методы манипуляции коэффициентом.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Monomial.h
> +Monomial<Field>::Monomial(Field coef, const MonomialDegree &degree) : coef_(coef), degree_(degree) {
Если конструктор принимает аргумент by value, то его надо мувать в поле класса, то есть coef_(std::move(coef)). Хорошо бы то же самое сделать для MonomialDegree.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Monomial.h
> +    return coef_ == other.coef_ && degree_ == other.degree_;
Ура, поздравляю тебя, это просто НЕ верная имплементация. Если у тебя коэффициенты будут ноль, а степени разные, то у тебя будет не верный ответ. Вот так вот писать кривые классы без инвариантов.

2024-03-09 16:36 UTC, DimaTrushin commented on src/ComparatorFwd.h
> +concept IsComparator = std::is_base_of_v<StraightOrder, T>;
чето опять какая-то хуйня, а не условие.

2024-03-09 16:36 UTC, DimaTrushin commented on src/GroebnerBuilder.cpp
Убери пустые cpp файлы, особенно если у тебя все на шаблонах.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialCompare.h
> +    const MonomialDegree &rhs_degree = rhs.GetDegree();
Как ты видишь, это НЕ порядки на мономах, а порядки на степенях. Тогда так и надо определить. Потому что когда ты добавляешь коэффициент, то подобным порядком ты не можешь сравнивать. У тебя если степени одинаковые, а коэффициенты разные получаются эквивалентные элементы.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialCompare.h
> +class StraightOrder {
Что это за порядок?

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialCompare.h
> +    return true;
это называется return lhs_degree == rhs_degree;

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialCompare.h
> +
Если я правильно понял, то lhs < rhs тогда и только тогда, когда все степени всех переменных в lhs строго меньше, чем в rhs. Но тогда тебя не смущает, что у тебя lhs == rhs НЕ эквивалентно !isLess(lhs, rhs) && !isLess(rhs, lhs)? То есть у тебя появляются эквивалентные, но не равные элементы и это НЕ согласуется оператором isEqual.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialCompare.h
> +bool StraightOrder::IsLessOrEqual(const Monomial<Field> &lhs, const Monomial<Field> &rhs) {
Ты понимаешь, что это не эквивалентно isLess(lhs, rhs) || isEqual(lhs, rhs)?

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialCompare.h
> +class LexOrder : public StraightOrder {
Нахуя, а главное зачем!? Если ты хочешь проверить является ли класс порядком, то проверяй наличие в нем нужных тебе методов, а не наследуй от какой-то неведомой хуйни, которую надо снести и никогда не вспоминать ни при каких условиях.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialCompare.h
> +        }
У меня такое ощущение, что люди внезапно забыли как программировать
```cpp
if (lhs_degree[i] != rhs_degree[i]) 
  return lhs_degree[i] < rhs_degree[i];
```
А вообще есть std::lexicographical_compare. Только им надо правильно воспользоваться.

2024-03-09 16:36 UTC, DimaTrushin commented on src/MonomialCompare.h
> +
Почему нельзя написать просто
```cpp
return isLess(lhs, rhs) || isEqual(lhs, rhs);
```
?? Тогда это хотя бы будет сходиться с названием.

2024-03-09 16:36 UTC, DimaTrushin commented on src/PolySystem.h
> +    PolySystem &operator=(PolySystem<Field, Comparator> &&other) noexcept = default;
Если все дефолтное, то не надо их вообще тут писать. Пусть компилятор создаст дефолтную версию за тебя неявно. Это всегда лучше.

2024-03-09 16:36 UTC, DimaTrushin commented on src/PolySystem.h
> +    // TODO add constructor from vector of polynomials
Плохо использовать конкретный вид контейнера в интерфейсе. Используй как минимум итераторы.

2024-03-09 16:36 UTC, DimaTrushin commented on src/PolySystem.h
> +    // TODO move in private and give access via friend
В чем проблема?

2024-03-09 16:36 UTC, DimaTrushin commented on src/PolySystem.h
> +    void Add(const Polynomial<Field, Comparator> &other);
Заведи using для типа многочленов, а то параметры шаблона отвлекают от чтения кода.

2024-03-09 16:36 UTC, DimaTrushin commented on src/PolySystem.h
> +    explicit PolySystem(const std::vector<Polynomial<Field, Comparator>> &polys);
Почему не от rvalue? Плохо.

2024-03-09 16:36 UTC, DimaTrushin commented on src/PolySystem.h
> +    return polynomials_ == other.polynomials_;
То есть ты учитываешь порядок, в котором хранятся твои многочлены? То есть две системы одних и тех же многочленов в разном порядке считаются у тебя разными?

2024-03-09 16:36 UTC, DimaTrushin commented on src/PolySystem.h
> +size_t PolySystem<Field, Comparator>::GetSize() const {
Ну вот ты тут уже не испльзуешь свой замечательный и никому ненужный тип SizeType.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +    // TODO add constructor for std::vector<>&&
Ну надо же.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +    Polynomial &operator=(Polynomial &&other) = default;
Убрать.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +    Polynomial<Field, Comparator> &operator*=(const Polynomial<Field, Comparator> &other);
Думабю тебе понадобится в будущем умение прибавлять к полиному коэффициент и произвольный моном, чтобы не строить явно полином и потом прибавлять.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +    void SortMonomials();
А ты не хочешь сделать инваривантом класса сортировку? Или это дорого?

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +    // no monomials with coefficient 0
Опомнился.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +    const Field coef = GetLeader().GetCoef();
const Field& или const Field? Это намерено или тут ошибка?

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +        monomials_[i].GetCoef() /= coef;
Тебе должно хватить оператора доступа к коэффициенту. И обрати внимание на сколько убого смотрится get в этом названии Coef() было бы куда лучше.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +const Monomial<Field> &Polynomial<Field, Comparator>::GetLeader() const {
Плохо что метод не безопасный. Вообще говоря пользователь очень удивится, что у нулевого многочлена нельзя взять лидера. Но тут не понятно, как правильно решать эту проблему. Можно как вариант вернуть ссылку на статический приватный моном равный нулевому моному без переменных.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +Polynomial<Field, Comparator>::Polynomial(const std::vector<Monomial<Field>> &monomials) {
Твоя имплементация никак не использует вектор. Ты бы мог с таким же успехом принимать просто два итератора на begin и end.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +        if (Comparator::IsEqual(monomials_[left], other.monomials_[right])) {
Обрати внимание, что straight order тут не сработает.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +
Чет какая-то мутная хуйня тут происходит.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +            // TODO std move if this != &other
Чет ты оплошал. Все время проверял на неравенство самому себе, а тут не поставил этот частный случай в виде оптимизации.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +        result += Polynomial<Field, Comparator>(row);
Во-первых, твой конструктор принимает вектор по константной ссылке и тут лишнее копирование.
Во-вторых, у тебя конструктор не проверяет, что мономы могут в векторе повторяться (точнее бывают мономы с разными коэффициентами, но одинаковыми переменными частями, а при перемножении такое получается с вероятностью 1). Так что ты строишь многочлен, в котором опять нет никаких инвариантов.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +
Судя по всему код выше предполагает, что момномы в многочленах отсортированы (я только не понял по возрастанию или убыванию) и не дублируются их переменные (то есть x^2y^3 не встречается несколько раз с какими-то коэффициентами). Но эти условия не гарантируется, что будут выполнены. У тебя опять некорректный недоделанный полукласс получился.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +    return monomials_ == other.monomials_;
Вот это просто фейс палм. То есть у тебя на самом деле не многочлены сравниваются, а многочлены с фиксированным порядком мономов внутри него. Потому что если у тебя одни и те же мономы лежат в разных порядках, то у тебя такие многочлены будут объявлены разными. А это фейл. Я удивляюсь, как вообще у тебя хоть что-то работает.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Polynomial.h
> +    });
Что мешало написать?
```cpp
std::sort(monomials_.begin(), monomials_.end(), &Comparator::IsGreater);
```
?

2024-03-09 16:36 UTC, DimaTrushin commented on src/Rational.h
> +    // zero as represented as 0 / 1
is

2024-03-09 16:36 UTC, DimaTrushin commented on src/Rational.h
> +    Rational(Rational &&other) noexcept;
Чем тебя не устраивает дефолтная имплементация?

2024-03-09 16:36 UTC, DimaTrushin commented on src/Rational.h
> +    bool operator==(const Rational &other) const;
А чем так перед тобой провинился оператор !=, что ты его нигде не используешь?

2024-03-09 16:36 UTC, DimaTrushin commented on src/Rational.cpp
> +    Rational::ValueType FindGcd(Rational::ValueType x, Rational::ValueType y) {
Чем тебе std::gcd не угодил?

2024-03-09 16:36 UTC, DimaTrushin commented on src/Rational.cpp
> +        return x * y / FindGcd(std::abs(x), std::abs(y));
Плохо. Это говно умрет от переполнения, когда ты x и y умножишь друг с другом. Тебе надо сначала поделить один из них на gcd, а только потом умножать. Поставь скобки правильно. Опять же не ясно чем тебе std::lcm не угодил.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Rational.cpp
> +    if (this != &other) {
С std::exchange нет необходимости в проверке на самоприсваивание, это всегда работает.

2024-03-09 16:36 UTC, DimaTrushin commented on src/Rational.cpp
> +    return numerator_ * (lcm / denominator_) <= other.numerator_ * (lcm / other.denominator_);
Все эти операторы должны быть выражены через <.

2024-05-10 16:04 UTC, merged

2024-05-16 15:19 UTC, DimaTrushin reviewed
Я это прочитал =)

Набросал разных комментариев больших и маленьких.

2024-05-16 15:19 UTC, DimaTrushin commented on CMakeLists.txt
> +add_subdirectory(Gtest)
новая строчка в конце каждого файла

2024-05-16 15:19 UTC, DimaTrushin commented on main.cpp
> +    out.close();
Не закрывай файловые потоки явно, они закрываются деструкторами автоматически. Это не сишные голые указатели на файловые дескрипторы.

2024-05-16 15:19 UTC, DimaTrushin commented on src/ComparatorFwd.h
> +concept IsComparator = Details::IsInList<T, Details::Comparators>;
Ну это скорее является ли компоратор зарегистрированным, а не просто является ли класс компоратором. Но я оценил подход через TypeList-ы.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Rational.h
> +        Rational operator+(const Rational& other) const;
Если у тебя конструкторы не explicit, то можно сделать бинарные операторы friend, то есть написать
```cpp
friend Rational operator+(const Rational& first, const Rational& second);
```
И тогда у тебя будет возможно писать
```cpp
Rational a;
Rational b = 4 + a;
```
То есть у тебя будет возможен каст по первому аргументу. Так как это все не дорого, то может быть разумно так сделать.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Rational.cpp
> +Rational::Rational(Rational::ValueType numerator,
Аргументы функций класса находятся внутри scope от данного класса. Потому тут можно НЕ писать квалификатор доступа Rational::, а просто написать ValueType.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Rational.cpp
> +    ValueType lcm = std::lcm(denominator_, other.denominator_);
неплох

2024-05-16 15:19 UTC, DimaTrushin commented on src/Rational.cpp
> +    numerator_ *= other.numerator_;
Если уж ты в сложении подумал про переполнение, то можно и тут сразу взять gcd для числителя this и знаменателя other и на них разделить и аналогично наоборот. И потом перемножить. Тогда у тебя и результат будет сразу взаимно простой и не надо будет reduce звать. И переполнение будет сильно позже происходить.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Rational.cpp
> +    // self-division case
Хорош, помоему я этот косяк у кого-то проглядел.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Rational.cpp
> +    return (*this < other) || (*this == other);
Можно еще проще, можно
```cpp
return !(other < *this);
```

2024-05-16 15:19 UTC, DimaTrushin commented on src/Modulo.h
> +        for (size_t i = 3; i * i <= n; i++) {
Тут можно написать i += 2, потому что тебе только по нечетным достаточно идти. И это ускорит компиляцию этого кода в два раза.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Modulo.h
> +requires IsPrime<Modulus> class Modulo {
хорош

2024-05-16 15:19 UTC, DimaTrushin commented on src/Modulo.cpp
> +    ModuloValueType gcd = FindGcdExtended(y % x, x, &temp_x, &temp_y);
А я уж думал тут будет цикл без рекурсии =)

2024-05-16 15:19 UTC, DimaTrushin commented on src/Modulo.h
> +        void Inverse() {
Любые методы, которые действуют inplace на объекте лучше писать так, чтобы они возвращали ссылку на *this. Тогда их можно чейнить спокойно.

2024-05-16 15:19 UTC, DimaTrushin commented on src/IteratorFwd.h
> +    T, typename std::enable_if<!std::is_same<
а что enable_if_t не пользуешься и аналогично is_same_v?

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.h
> +        VariableOrder(const VariableOrder& other);
У меня один вопрос. Зачем? У тебя и так все компоненты -- это объекты с value semantics, потому стандартно сгенерированные конструкторы годятся. А так у тебя потенциальное UB. А нет, у тебя просто ошибка линковки.

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.h
> +        static VariableOrder& Instance();
Я предпочитаю разделять код объекта и код для предоставления синглтона. То есть у меня скажем ситуация такая. Вот есть шаблонный код
```cpp
template<class Data, class Id>
class Singleton {
public:
  static Data& Instance() {
    static Data data;
    return data;
  }
};
```
И потом он используется так
```cpp
struct MainA;
class A {...};
using GlobalA = Singleton<A, MainA>;
GlobalA::Instance().func();
```
И так не надо специально класс затачивать под синглтонность. Ты просто можешь любой класс завернуть в синглтон, а в рамках класса ты уже решаешь только ту задачу, которой должен заниматься класс.
Второй параметр нужен, если я захочу создать два глобальных объекта типа A. Иначе синглтоны не различимы.

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.h
> +        void SetVarList(std::vector<var_pair>&& var_list);
У тебя нет никакого проку от этого конструктора. Он ничем не эффективнее, чем конструтор через initializer_list. Можно убрать.

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.h
> +        void SetVarList(std::initializer_list<var_pair> var_list);
Нет смысла тут использовать std::pair. Лучше сделай структуру
```cpp
struct Var {
  size_t index;
  std::string name;
};
```
И тут сделай функцию вида
```cpp
void SetVarList(std::initializer_list<Var> va_list);
```
Тогда пользователь будет писать так
```cpp
dictionary.SetVarList({Var{.index = 0, .name = "x"}, Var{.index = 1, .name = "y"}});
```
Хотя бы на стороне пользователя код будет содержать осмысленные имена. Кроме того, с точки зрения эффективности будет то же самое, потому что из std::initializer_list нельзя своровать данные, ты их все равно копируешь.

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.h
> +        std::string GetAt(size_t index);
А почему строку возвращаешь по значению, а не по константной ссылке?

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.cpp
> +    index_to_name_[index] = name;
Не используй оператор operator[] для помещения данных в std::map, используй try_emplace, который эффективнее, не вызывает лишние конструкторы, если элемент не надо вставить и ничего не делает, если элемент уже был
https://en.cppreference.com/w/cpp/container/map/try_emplace
Так же можно проверить, был ли элемент вставлен и вернуть флаг говорящий об этом.

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.h
> +        std::unordered_map<std::string, size_t> name_to_index_;
Кстати, а нет какой-то структуры данных которая за логарифм может находить пары по первой и по второй координате?

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.cpp
> +    assert(index_to_name_.contains(index) && "No such index");
Плохой дизайн. Это означает, что эта операция не безопасная. Но тогда ты должен пользователю предоставить возможность проверить можно ли ее вызывать. Кроме того, использование operator[] мешает тебе сделать эту операцию const каковой она должна быть. Потому тут придется использовать find. Но тогда все равно надо решить, что делать, если такого элемента нет. Как вариант тоже кидать assert, но добавить метод contains для проверки принадлежности элемента словарю.

2024-05-16 15:19 UTC, DimaTrushin commented on src/VariableOrder.h
> +        // TODO add checks for no conflicts
Да, проверки стоит добавить. Если ты хочешь хранить 1-1 соответствие, то просто так пихать все подряд сюда не стоит, у тебя сломаются инварианты.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +    requires Groebner::IsPrime<N> struct FieldPrinter<Modulo<N>> {
Это точно clang-format так отформатировал?

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +        std::ofstream* out_;
Почему принтер не владеет потоком? Это выглядит как ошибка особенно учитывая, что принтер является синлтоном. Это означает, что он потенциально переживет все локальные объекты и все локальные потоки и всегда будет момент, когда он ссылается на невалидную память. То есть можно было бы мувнуть нжный потк внутрь принтера. Это был бы куда более правильный value semantics дизайн.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +// TODO also add Details level
очень правильное замечание.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +        static PrinterBuffer& Instance() {
Этот класс не должен быть синглтоном. Это просто вспомогательный класс, который должен лежать внутри принтера. Из-за того, что ты не разделил логику синглтона и самого класса, то попал тут в ловушку.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +            PrintPolynomial(PrinterBuffer<Field, Comparator>::Instance()[0],
Храни буффер епосредственно в самом классе. Зачем тут синглтон?

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +                } else if (i > 0 && coef < 0) {
Вообще чтобы поддерживать любые виды коэффициентов любых классов, то можно сделать следующее. Создаешь прокси класс, который занимается првоеркой, нужно ли пиать + перед элементом или нет. И этот класс делаешь шаблонным. И для известных типов перегружаешь его так, что он например проверяет знак. А для других по дефолту всегда плюс добавляешь. А если такое поведение пользователю не нравится, он просто специализирует для своего класса этот прокси класс. Это такой класс адаптер, который помогает тебе взаимодействовать с неизвестным типом через известный тебе и ему тип с дефолтной имплементацией и специализацией для того, что ты уже предусмотрел.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +        enum NewLinePolicy {
Во-первых, лучше enum class, так как это не флаги, ты не делаешь с ними битовые операции.
Во-вторых, НЕ используй стиль CAPS_ONLY для чего либо кроме макросов. Так ты будешь сбивать с толку программистов, когда они будут читать твой код.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +        enum DescriptionLevel {
Я бы сделал этот enum без названия и завернул бы в структуру вот так
```cpp
struct DescriptionLevel {
enum {
  None = 0x0,
  Conditions = 0x1,
  Results = 0x2,
  Details = 0x4,
  All = Conditions | Results | Details
};
};
```
Тогда эти имена НЕ утекут в окружающий scope, а именно в Printer класс. То есть сейчас ты можешь написать код вида
```cpp
DescriptionLevel::None == Conditions;
```
и оно сработает, потому что ты можешь использовать имя как с квалификатором, так и без. Квалификатор тут нужен только чтобы можно было тип соответствующего выражения явно указать, но НЕ для ограничения доступа. Это тупо, но так это работает в Си. Потому C++ версия это enum class. Но когда нужны именно флаги, они не дают возможности делать над флагами операции, и потому надо заворачивать в структуру.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +        Printer& PrintPolynomial(const Polynomial<Field, Comparator>& poly,
А почему все методы имеют разное название? То есть бывает, что ты один и тот же тип хочешь печатать и как полином и как коэффициенты например? И в следствии вопрос, а почему вообще это делается не через оператор вывода operator<<? В него так же можно скармливать всякие модификаторы и потом пушить туда данные.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Printer.h
> +        std::vector<Polynomial<Field, Comparator>> buffer_;
Это какой-то очень специализированный буффер, который хранит именно многочлены. Можно как-то понять зачем он нужен? Почему просто хранить вектор в принтере не годится?

2024-05-16 15:19 UTC, DimaTrushin commented on src/Monomial.cpp
> +    }
Вот это плохо. Если у тебя первый вектор короче, чем второй, то вычесть просто нельзя. Это проверяет ассерт выше. У тебя этот код никогда не должен выполниться при наличии ассерта. Не проверяй условия, которые гарантирует ассерт.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Monomial.cpp
> +        SetDegree(i, GetDegree(i) - other.GetDegree(i));
Я думаю, что так как тут мы знаем, что не выйдем за границы массива, можно имплементировать с помощью оператора доступа к элементу вектора. Аналогично со сложением. Просто избавимся от лишних проверок в цикле.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Monomial.cpp
> +Monomial::Monomial(size_t size) : degrees_(size) {}
А ты не хочешь поддерживать инвариант, что последняя координата не нулевая? Тогда это сильно упростит тебе жизнь.

2024-05-16 15:19 UTC, DimaTrushin commented on src/MonomialCompare.cpp
> +    return true;
Если поддерживать инвариант, что последняя координата не ноль, то это одна строчка
```cpp
return lhs.degrees_ == rhs.degrees_;
```
Либо с оптимизацией
```cpp
return lhs.sum_degree_ == rhs.sum_degree_ && lhs.degrees_ == rhs.degrees_;
```

2024-05-16 15:19 UTC, DimaTrushin commented on src/MonomialCompare.h
> +class ReverseLexOrder : public StraightCoordinateOrder {
Зачем публичное наследование? Зачем тут вообще наследование? Ты же можешь дернуть любой метод из этого класса и так.

2024-05-16 15:19 UTC, DimaTrushin commented on src/MonomialCompare.h
> +#include <cassert>
перенеси в cpp файл, тут этот хедер лишний и не используется.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Monomial.h
> +        }
```cpp
Monomial(It begin, It end)
  : sum_degree_(std::accumulate(begin, end, 0ull))
  , degrees_(begin, end) {}
```
Используй список инициализации. Проверяй какие конструкторы есть у тех или иных классов на cppreference. Старайся по минимуму использоавть тело конструктора.

И еще тут лучше не использовать явно 0ull, потому что мало ли ты сменишь тип на другой. Лучше будет написать DegreeType(0).

2024-05-16 15:19 UTC, DimaTrushin commented on src/Monomial.cpp
> +Monomial::Monomial(std::vector<DegreeType>&& degrees)
Этот надо убрать.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Monomial.cpp
> +    sum_degree_ = std::accumulate(degrees_.begin(), degrees_.end(), 0ULL);
Пененеси все в список инициализации.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +using RationalTerm = Term<Rational>;
Зачем это тут?

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +requires IsPrime<N> using ModuloTerm = Term<Modulo<N>>;
Зачем это тут?

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +struct Term {
Почему это не в отдельно хедере?

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +        Term<Field>& operator/=(const Term& other) {
Если уж определяешь методы, то определяй все, что нужно включая умножение термов.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +        // TODO add constructor from Polynomial with different comparator
Разумно

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +                    monomials_[std::move(degree)] = std::move(coef);
замени на try_emplace

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +        explicit Polynomial(std::vector<LocalTerm>&& monomials) {
Не понятно зачем нужен такой конструктор. Я понимаю если бы ты съедал std::map, который хранится, чистил бы его и присваивал многочлену. Но тогда этот конструктор скорее всего был бы приватным и использовася бы внутри методов. И это было бы эффективно. А тут какая-то странная дичь, которая непонятно когда нужна.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +        LocalTerm GetAt(size_t i) const {
Можно завести статическую переменную в виде нулевого терма и возвращать ссылку на него если объекта нет или возвращать ссылку на нужный терм, если он есть.

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +            }
А почему здесь не используется прибавление термов, которое имплементированно ниже?

2024-05-16 15:19 UTC, DimaTrushin commented on src/Polynomial.h
> +            }
А не хочешь добавить операции деления, умножения и прибавления константы из поля?

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +                if (!poly.IsZero()) {
То есть тебя не волнует если многочлены повторяются, главное чтобы не ноль?

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +        std::vector<LocalPolynomial> polynomials_;
А вектор, потому что нет компоратора для многочленов и он дорогой?

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +        explicit PolySystem(std::vector<LocalPolynomial>&& polys) {
А ты не сортируешь никак многочлены в этом множестве?

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +            polynomials_.reserve(polys.size());
Использование reserve, это чуть ли не единственный случай, когда можно пользоваться телом конструктора.

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +            polynomials_.push_back(other);
А тут проверку на нулевой не делаешь? У тебя ломается инвариант!

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +            polynomials_.erase(std::next(polynomials_.begin(), index));
А нахрена тут std::next, если ты хочешь удалить именно begin() + index? Чего я не понимаю?

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +
Я бы ожидал еще методы вроде replace, где ты добавляешь элемент и заменяешь им элемент на каком-то месте.

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +    friend class GroebnerAlgorithm;
А точно это надо? Чего тебе не хватает в интерфейсе многочленов для работы с ними?

2024-05-16 15:19 UTC, DimaTrushin commented on src/PolySystem.h
> +            size_t sz = polynomials_.size();
Есть же std::remove_if

2024-05-16 15:19 UTC, DimaTrushin commented on src/GroebnerAlgorithm.h
> +        static void BuildGBInplace(
Я не увидел, а где тут происходит вычисление базиса гребнера? Тут  авторедукция какая-то происходит.

2024-05-16 15:19 UTC, DimaTrushin commented on src/GroebnerAlgorithm.h
> +                AddRemindersToPolyAtPos(i, poly_system);
Вот этот метод имеет плохое название. В нем как раз выполняется работа из алгоритма бухбергера. Надо подумать как назвать.

2024-05-16 15:19 UTC, DimaTrushin commented on src/GroebnerAlgorithm.h
> +                    assert(!poly_system[i].GetLeader().coef.IsZero() &&
Вот мне всегда не нравился код такого вид x.y.z.w.u.v.function() Это нарушение уровня доступа, у тебя классы не имеют нормальных интерфейсов для взаимодействия и ты потому лезешь в кишки этих классов, чтобы работать с ними. Прекращай харакири над классами.

2024-05-16 15:19 UTC, DimaTrushin commented on src/GroebnerAlgorithm.h
> +                    temp.Add(basis[i]);
жаль что тут копия делается.

2024-05-16 15:19 UTC, DimaTrushin commented on src/GroebnerAlgorithm.h
> +            // TODO add poly_system.reduce()
подерживай это свойство как инвариант класса систем. И запрети этому классу копаться в кишках класса систем и тогда этот инвариант не будет нарушен.

2024-05-16 15:19 UTC, DimaTrushin commented on src/GroebnerAlgorithm.h
> +            basis = PolySystem<Field, Comparator>();
охуеть у тебя inplace

2024-05-16 15:19 UTC, DimaTrushin commented on src/GroebnerAlgorithm.h
> +            basis = PolySystem<Field, Comparator>();
А я поял, что тут происходит, это происходит авторедукция нестарших членов.

2024-05-16 15:19 UTC, DimaTrushin commented on src/GroebnerAlgorithm.h
> +            PrinterBuffer<Field, Comparator>::Instance().SetBuffer(
Это что еще за хень? С чего вдруг тут это нужно? Почему этим надо управлять снаружи. Это же какая-то делать имплементации. Ну и даже если так, то какого хрена это не через Printer::Instance() делается? Это звиздец как выносит мозг, это нарушение локальности и это худшее взаимодействие синглтонов, которое я когда либо видел. люс это вообще читать не возможно.